### ISSUE TITLE
Tamil glyphs in built Fonts don't have a unicode value.

### ISSUE THREAD

**Issue by pathumego** [mooniak/ayanna-narrow#16]
<img width="521" alt="screen shot 2015-10-11 at 10 20 07 pm" src="https://cloud.githubusercontent.com/assets/6846609/10419155/431b9b3e-7066-11e5-9f76-5370d72b3549.png">

**Comment by paarandika** [comment]
This is already corrected on SNB. I haven't started working on Ayanna Tamil yet. Not enough glyphs to work with.
